run_as shiny;

server {
  listen 3838;
  site_dir /srv/shiny-server;
  log_dir /var/log/shiny-server;
  directory_index on;

  location / {
    app_dir /srv/shiny-server;
    log_dir /var/log/shiny-server;
  }

  location /crd-rbd {
    app_dir /srv/shiny-server/crd-rbd;
    log_dir /var/log/shiny-server;
  }

  location /factorial-design {
    app_dir /srv/shiny-server/factorial-design;
    log_dir /var/log/shiny-server;
  }

  location /pooled-anova {
    app_dir /srv/shiny-server/pooled-anova;
    log_dir /var/log/shiny-server;
  }

  location /split-plot {
    app_dir /srv/shiny-server/split-plot;
    log_dir /var/log/shiny-server;
  }

  location /correlation-regression {
    app_dir /srv/shiny-server/correlation-regression;
    log_dir /var/log/shiny-server;
  }
}
